name: quality

on:
  push:
    branches: [main, dev, "feat/**", "fix/**"]
  pull_request:
    branches: [main, dev]

jobs:
  hygiene:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml

      - name: Generate SBOM
        id: sbom
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: sbom.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: ${{ steps.sbom.outputs.sbom-path }}

      - name: Placeholder lint
        run: |
          echo "TODO: Add linting once code exists"
